### ISSUE TITLE
Qt5.5.0 doesn't run debug my project

### ISSUE THREAD

**Issue by SalahAdDin** [fire/QtCreatorSourceCodeAccess#10]
I have many hours trying build an Unreal Project with QtCreator and i can't do it.

I compile entire editor with this plugin included, i see the video and do all steps very well and i have nothing!

See:
![hero pro - hero - qt creator_022](https://cloud.githubusercontent.com/assets/5034215/9974620/2617047a-5e5e-11e5-914a-1910bcdae047.png)
![hero pro - hero - qt creator_023](https://cloud.githubusercontent.com/assets/5034215/9974617/261088c0-5e5e-11e5-8c4f-2ebe4dc388a8.png)
![hero pro - hero - qt creator_024](https://cloud.githubusercontent.com/assets/5034215/9974618/2611bc68-5e5e-11e5-8c96-058dd690437c.png)
![hero pro - hero - qt creator_025](https://cloud.githubusercontent.com/assets/5034215/9974619/261254d4-5e5e-11e5-9f06-066e4d6342ce.png)
![hero - qt creator_021](https://cloud.githubusercontent.com/assets/5034215/9974621/261d71b6-5e5e-11e5-9a98-632f76f91e44.png)

There are the General Messages:
```bash
Could not find qmake configuration file default.
Error while parsing file /media/tulipan/Datos/Proyectos/Personal/Unreal Projects/Hero/Hero.pro. Giving up.
Warnings while parsing QML type information of /home/tulipan/Qt/5.5/gcc_64/qml:
<dump of /home/tulipan/Qt/5.5/gcc_64/qml>:1:24: Reading only version 1.1 parts.
<dump of /home/tulipan/Qt/5.5/gcc_64/qml>:10:5: Expected only Component and ModuleApi object definitions.
```

And this is the Compile Output:
```bash
22:06:18: Running steps for project Hero...
22:06:18: Starting: "/home/tulipan/Qt/5.5/gcc_64/bin/qmake" '/media/tulipan/Datos/Proyectos/Personal/Unreal Projects/Hero/Hero.pro' -r -spec linux-clang CONFIG+=debug
22:47:16: The process "/home/tulipan/Qt/5.5/gcc_64/bin/qmake" crashed.
22:47:16: Canceled build/deployment.
22:47:16: Elapsed time: 40:58.
```
I had to kill the process, can you see? 40 minutes!!!

I'm not understand what happen, i can open the Editor manually from terminal, but not from QtCreator!

As you can see i have Clang 3.6 and QtCreator 3.5 with Qt 5.5.

Thanks for your help.

**Comment by SalahAdDin** [comment]
Hello :+1:

**Comment by fire** [comment]
I believe only clang 3.5 works with Unreal. Can you try that?

**Comment by fire** [comment]
Also can you try opening the cmakefile?

**Comment by SalahAdDin** [comment]
Which is the command to do this?
When i compile UnrealEngine using the tutorial yes, make all files, when i do ./UE4Editor, yes, run, but when i try run debug in qtcreator, fails :'(

**Comment by fire** [comment]
I don't know what command qtcreator uses to run a program. It needs to change to the Engine/Binaries/Linux directory and run the ./ue4editor <NAME OF GAME PROEJCT>

**Comment by fire** [comment]
Try newest version, if it doesn't work open a bug.
