### ISSUE TITLE
Unable to find a Source IDE.

### ISSUE THREAD

**Issue by SalahAdDin** [fire/QtCreatorSourceCodeAccess#11]
We are now in 4.9 release version and this error continues here: https://answers.unrealengine.com/questions/182813/no-compiler-was-found-1.html

I try do the same and i get these error:
![mensaje_020](https://cloud.githubusercontent.com/assets/5034215/9974654/e7048b66-5e5f-11e5-9b5c-f400434d1ae0.png)

**Comment by SalahAdDin** [comment]
I think that i find your error, your problem, or, our problem is that /usr/bin/qtcreator doesn't exist, but, why?
It's simple qt installer in ubuntu say us that we should install qtcreator in our personal folder, in my case is tulipan, so, the really qtcreator path is /home/tulipan/Qt/Tools/QtCreator/bin, that it's very diferent or your path, change the way to get this path will be better!

**Comment by fire** [comment]
One way would be to add qtcreator to the PATH another would be an environmental variable or a variable for the editor.

I have to investigate which method is better.

**Comment by fire** [comment]
Try newest version, if it doesn't work open a bug.

**Comment by SalahAdDin** [comment]
The newest version of your plugin or a newest version of unreal?

**Comment by fire** [comment]
The newest version my plugin and 4.10.1 / 4.10.0.
