### ISSUE TITLE
Update to 4.11

### ISSUE THREAD

**Issue by fire** [fire/QtCreatorSourceCodeAccess#18]
Discover what is needed for 4.11

**Comment by Ainias** [comment]
For me, adding 

`if (UEBuildConfiguration.bBuildEditor)
			{
				PrivateDependencyModuleNames.Add("HotReload");
			}`

after 
`PrivateDependencyModuleNames.AddRange(
                                new string[]
				{
					"Core",
					"DesktopPlatform",
					"SourceCodeAccess"
				}
			);`

in QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/QtCreatorSourceCodeAccess.Build.cs

[QtCreatorSourceCodeAccess.Build.cs.zip](https://github.com/fire/QtCreatorSourceCodeAccess/files/233139/QtCreatorSourceCodeAccess.Build.cs.zip)


fixes the problem

**Comment by fire** [comment]
Too old.
