### ISSUE TITLE
Space in path breaks loading project.

### ISSUE THREAD

**Issue by Zerophase** [fire/QtCreatorSourceCodeAccess#19]
Unreal puts a space in the default path for Projects. This breaks the accessor.

**Comment by fire** [comment]
Thanks for the report. If you can patch this on your own, I'll be grateful. 

I'm busy this weekend and in general don't have much work bandwidth.

**Comment by Zerophase** [comment]
I'll look into it. It looks like there should already be a fix in the accessor. Do I need to compile the accessor separate from the Unreal compile?

**Comment by Zerophase** [comment]
Think the issue might be something internal to Unreal.

Here's the log from opening a file:

> [2016.06.10-04.57.47:983][523]LogHAL: FLinuxPlatformProcess::CreateProc: '/usr/bin/qtcreator -client "/home/zerophase/Documents/Unreal Projects/MyProject/Source/MyProject/MyClass.h"'
> [2016.06.10-04.57.47:983][523]LogHAL: FLinuxPlatformProcess::CreateProc: spawned child 8979
> [2016.06.10-04.57.47:983][523]LogHAL: FLinuxPlatformProcess::CreateProc: '/usr/bin/qtcreator -client "/home/zerophase/Documents/Unreal Projects/MyProject/Source/MyProject/MyClass.cpp"'
> [2016.06.10-04.57.47:984][523]LogHAL: FLinuxPlatformProcess::CreateProc: spawned child 8980
> 
> (process:8982): Gtk-WARNING **: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> 
> (process:8981): Gtk-WARNING **: Locale not supported by C library.
> 	Using the fallback 'C' locale.

**Comment by fire** [comment]
weird.

**Comment by fire** [comment]
Updated patch to latest.
