### ISSUE TITLE
Issue with  4.12.5

### ISSUE THREAD

**Issue by new-gen23** [fire/QtCreatorSourceCodeAccess#20]
Error Message:
LogModuleManager:Warning: ModuleManager: Unable to load module 'QtCreatorSourceCodeAccess' because the file '/usr/local/share/UE/UnrealEngine/Engine/Binaries/Linux/' was not found.

In the Readme it says:
"Compile the plugin. May require a full recompile of the editor. (Restart editor)"

How?

**Comment by damasko** [comment]
Hi, I have the same problem, did you solved the problem?

**Comment by DrogonMar** [comment]
Ok, so in you're engine's main dir where Setup.sh and GeneratreProjectFiles.sh is you want to run `make UE4Editor` and that will compile the editor with the plugins. :)

**Comment by fire** [comment]
Too old. Closing.
