### ISSUE TITLE
Header "ModuleManager.h" not found

### ISSUE THREAD

**Issue by jurassicLizard** [fire/QtCreatorSourceCodeAccess#28]
UE Version : 4.21.1

The module failed to build out of the box because of not finding said header until i changed the include under

QtCreatorSourceCodeAccess/Source/QtCreatorSourceCodeAccess/Private/QtCreatorSourceCodeAccessPrivatePCH.h

to 

`Modules/ModuleManager.h`

Just a heads up.

**Comment by fire** [comment]
Collapsing into one issue.
