### ISSUE TITLE
Fails to load on 4.20.3

### ISSUE THREAD

**Issue by medusa606** [fire/QtCreatorSourceCodeAccess#29]
Can build this after making changes to "ModuleManager.h" as in #28.
Application starts to loads and gives a warning about running a plugin for 4.18.
Then "Plugin failed to load because module 'QtCreatorSourceCodeAccess' could not be found..."
on Ubuntu 16.04LTS using qtcreator 4.8.0

**Comment by fire** [comment]
Try the latest. I don't use Linux as often anymore.

**Comment by fire** [comment]
I've stopped work on my Unreal Engine tools. Sorry if it affects you.
