### ISSUE TITLE
QtCreator does not open

### ISSUE THREAD

**Issue by Pymann** [fire/QtCreatorSourceCodeAccess#32]
Hi guys,

i was able to compile,install and enable your plugin. But the qt-creator does not start when hitting:
'Open Qt Creator'

I'm using qt 5.17.2 meanwhile its LTS version
and Unreal Engine 4.24.2-0

**Comment by fire** [comment]
Sorry, I haven't been using Unreal Engine for nearly two years.

**Comment by fire** [comment]
I've stopped work on my Unreal Engine tools. Sorry if it affects you.
