### ISSUE TITLE
UE4 Editor Can't Find Qt Creator

### ISSUE THREAD

**Issue by jtmayer** [fire/QtCreatorSourceCodeAccess#5]
I keep getting an error in the lower left part of the screen:
```
Could not edit the code editing IDE. /home/me/Programs/Unreal4/Projects/Test/ could not be found.
```

Test is the name of my Project.

I am using Qt Creator 3.0.1 (from apt-get install), the "release" branch for UE4, and the "4.6" branch for this repo. I changed the Engine/Config/Linux/LinuxEngine.ini file, and ran make UE4Editor as stated here: 
https://wiki.unrealengine.com/Linux_Known_Issues#Running_2

**Comment by fire** [comment]
Can you visit #ue4linux on freenode? I usually idle there.

**Comment by fire** [comment]
Other people say this works with 4.7 though. Perhaps the 4.6 branch is out of date.

**Comment by jtmayer** [comment]
Can confirm that it works with 4.7.
