### ISSUE TITLE
Not identifying clang

### ISSUE THREAD

**Issue by cyborgmuppet** [fire/QtCreatorSourceCodeAccess#6]
Hi!

On my system there was no clang file, so I had to make the link clang reffering to clang-3.5.
Is it an idea to change the code, using regex to just identify "clang<whatever>"?

Best regards

**Comment by fire** [comment]
It might be possible to check for both clang or clang-3.5 in the code. I'll investigate.

**Comment by fire** [comment]
I've changed the check to clang++. Please see if it works on your machine.

**Comment by SalahAdDin** [comment]
Are you created a new kit with clang compiler by default?

**Comment by cyborgmuppet** [comment]
Hi!

I think this is a old issue, I don't even remember what the issue was.
You should probably not follow this.

But thanks :)

Kind regards
Ove M Henriksen

On Sat, Sep 19, 2015 at 6:18 AM, Yusuf (Josè) Luis <notifications@github.com

**Comment by SalahAdDin** [comment]
I can't build and run the Editor with QtCreator, you could do it?
Are you workin in OsX, Windows or Linux?

**Comment by cyborgmuppet** [comment]
I don't remember.

I were working in Linux

On Mon, Sep 21, 2015 at 8:06 PM, Yusuf (Josè) Luis <notifications@github.com

**Comment by fire** [comment]
```
cd /usr/bin/
sudo ln -s clang-3.5 clang```

This is probably the command.

**Comment by SalahAdDin** [comment]
For what man? 
My problem is in QtCreator with build and run the project, i configured all but doesn't work.
