### ISSUE TITLE
Assignment of license under MIT license

### ISSUE THREAD

**Issue by fire** [fire/QtCreatorSourceCodeAccess#7]
@cybik @salamanderrake, I'm trying to make sure this code is under the mit license. 

Can you reaffirm that what both of you wrote as assigned to me under mit license?

**Comment by salamanderrake** [comment]
Yes I can affirm what I wrote to you is under the MIT license.

**Comment by cybik** [comment]
I hereby affirm it.

**Comment by fire** [comment]
Closed.
